# Generated by Django 3.1.7 on 2021-12-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='uuid',
            new_name='entity_id',
        ),
    ]
