# Generated by Django 3.2.8 on 2021-11-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='replied_id',
            field=models.IntegerField(null=True),
        ),
    ]
