# Generated by Django 3.2.8 on 2021-11-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20211115_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_replied',
            new_name='has_replied',
        ),
    ]
