# Generated by Django 3.2.8 on 2021-11-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20211120_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
